### ISSUE TITLE
Refresh page when the "refresh icon" at the top right corner is clicked + Hard refresh

### ISSUE THREAD

**Issue by ch3nkula** [ch3nkula/awmd-stats#16]
Refresh the stats page or any page when the refresh icon at the top right corner of the page is clicked.

NOTE: Hard refresh also needed, so task has been reopened!

**Comment by ch3nkula** [comment]
Fix here: #17. 👍

**Comment by ch3nkula** [comment]
Reopening this issue! Hard refresh needed and not soft refresh!

**Comment by samuelguebo** [comment]
Was fixed in #27
