### ISSUE TITLE
Coding convention and style in the entire repo

### ISSUE THREAD

**Issue by xSavitar** [ch3nkula/awmd-stats#2]
Concentrate on coding style and convention. @samuelguebo, let me handle this and we'll just pick up from there. :)

**Comment by samuelguebo** [comment]
@ch3nkula As for the coding convention I have been following the [official guide from WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/). Maybe because it's PHP won't really apply. Will it?

**Comment by xSavitar** [comment]
Imported to phabricator, see here: https://phabricator.wikimedia.org/T202229, can now close this!
